name: OpenSSF Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '20 7 * * 2'
  push:
    branches: [ "main" ]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: "Checkout code"
        uses: actions/checkout@eef6142766c827365c40131433f524aeefef9662 # v4.1.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload artifact"
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea23f8d10f0974f0d015248fc # v4.4.3
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@6bb03432bb3f90b107bc6f22660d0295d73b068e # v3.25.10
        with:
          sarif_file: results.sarif
